# Day1: Python for AI + Prompt Engineering
Date: June 26, 2026 
Goal: numpy/pandas basic + 4 prompt experiments

## Numpy - The Basics
Numpy's main objective is the 'Homogeneous multidimensional array'. Numpy's array class is called "ndarray". It is also known by the alias "array". The most important attributes of an "ndarray" object are:

# ndarray.ndim
The number of axes (dimensions) of the array.
# ndarray.shape
This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, "shape" will be (n,m).
# ndarray.size
The total number of elements of the array. This is equal to the product of the elements of "shape".
# ndarray.dtype
An object describing the type of the elements in the array. One can create or specify dtype's using standard Python types.
# ndarray.itemsize
The size in bytes of each element of the array. For example, an array of elements of type "float64" has "itemsize=8"(=64/8)
# ndarray.data
The buffer containing the actual elements of the array. Normally, we won't need to use this attribute because we will access the elements in an array using indexing facilities.

# NOTE:
1. "numpy.array" is not the same as the Standard Python Library class "array.array", which only handles one-dimensional arrays and offers less functionality.

In [15]:
import numpy as np
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
arr.shape

(3, 5)

In [4]:
arr.ndim

2

In [6]:
arr.dtype

dtype('int64')

In [7]:
arr.itemsize

8

In [8]:
arr.size

15

In [9]:
type(arr)

numpy.ndarray

In [10]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [11]:
type(b)

numpy.ndarray

## Array Creation
There are several ways to create arrays.

You can create an array from a regular Python list or tuple usingthe "array()".

In [16]:
arr1 = np.array([2,3,4])
arr1

array([2, 3, 4])

The type of the resulting array is deduced from the type of the elements in the sequences.

In [17]:
arr1.dtype

dtype('int64')

In [18]:
b=np.array([1.2,3.5,5.1])
b.dtype

dtype('float64')

A frequent error consists in calling "array" with multiple arguments, rather than providing a single sequence as an argument.

In [19]:
arr2=np.array(1,2,3,4) # WRONG

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [20]:
arr2=np.array([1,2,3,4])
arr2

array([1, 2, 3, 4])

"array" transforms sequences of sequences into 2D arrays, sequences of sequences of sequences into 3D arrays, and so on.

In [21]:
arr3=np.array([(1.5,2,3),(4,5,6)])
arr3

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

The type of the array can also be explicitly specified at creation time:

In [22]:
arr4=np.array([[1,2],[3,4]],dtype=complex)
arr4

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function 'zeros' creates an array full of zeros, the function 'ones' creates an array full of ones, and the function 'empty' creates an array whose initial content is random and depends on the state of the memory.

# note: 
By default, the dtype of the created array is 'float64', but it can be specified via the key word argument 'dtype'.

In [31]:
arr5=np.zeros((3,4),dtype=np.int16)
arr5

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [27]:
arr6=np.ones((2,3,4),dtype=np.int16)
arr6

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [33]:
arr7=np.empty((2,3),dtype=np.int64)
arr7

array([[4609434218613702656, 4611686018427387904, 4613937818241073152],
       [4616189618054758400, 4617315517961601024, 4618441417868443648]])

To create sequences of numbers, NumPy provides the "arange" function which is analogous to the Python built-in "range", but returns an array.

In [34]:
arr8=np.arange(10,30,5)
arr8

array([10, 15, 20, 25])

In [35]:
arr9=np.arange(0,2,0.3) #it accepts float arguments
arr9

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When 'arange' is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision.

For this reason, it is usually better to use the function 'linspace' that receives as an argument the no.of elements that we want, instead of the step:

In [36]:
from numpy import pi
arr10=np.linspace(0,2,9)  # 9 numbers from 0 to 2
arr10

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
x=np.linspace(9,2*pi,100) # useful to evaluate function at lots of points.
f=np.sin(x)
f

array([ 4.12118485e-01,  4.36963933e-01,  4.61480326e-01,  4.85649203e-01,
        5.09452362e-01,  5.32871880e-01,  5.55890120e-01,  5.78489748e-01,
        6.00653746e-01,  6.22365423e-01,  6.43608430e-01,  6.64366768e-01,
        6.84624807e-01,  7.04367291e-01,  7.23579353e-01,  7.42246525e-01,
        7.60354750e-01,  7.77890392e-01,  7.94840246e-01,  8.11191547e-01,
        8.26931982e-01,  8.42049698e-01,  8.56533311e-01,  8.70371913e-01,
        8.83555084e-01,  8.96072896e-01,  9.07915923e-01,  9.19075245e-01,
        9.29542461e-01,  9.39309686e-01,  9.48369567e-01,  9.56715281e-01,
        9.64340542e-01,  9.71239609e-01,  9.77407287e-01,  9.82838930e-01,
        9.87530449e-01,  9.91478311e-01,  9.94679542e-01,  9.97131732e-01,
        9.98833035e-01,  9.99782169e-01,  9.99978420e-01,  9.99421639e-01,
        9.98112246e-01,  9.96051227e-01,  9.93240135e-01,  9.89681085e-01,
        9.85376758e-01,  9.80330396e-01,  9.74545799e-01,  9.68027322e-01,
        9.60779874e-01,  9.52808914e-01,  9.44120443e-01,  9.34721005e-01,
        9.24617677e-01,  9.13818069e-01,  9.02330312e-01,  8.90163057e-01,
        8.77325467e-01,  8.63827209e-01,  8.49678449e-01,  8.34889840e-01,
        8.19472519e-01,  8.03438097e-01,  7.86798648e-01,  7.69566701e-01,
        7.51755235e-01,  7.33377661e-01,  7.14447819e-01,  6.94979963e-01,
        6.74988755e-01,  6.54489248e-01,  6.33496880e-01,  6.12027458e-01,
        5.90097151e-01,  5.67722472e-01,  5.44920272e-01,  5.21707720e-01,
        4.98102298e-01,  4.74121781e-01,  4.49784228e-01,  4.25107966e-01,
        4.00111577e-01,  3.74813885e-01,  3.49233941e-01,  3.23391007e-01,
        2.97304544e-01,  2.70994197e-01,  2.44479778e-01,  2.17781254e-01,
        1.90918731e-01,  1.63912437e-01,  1.36782709e-01,  1.09549977e-01,
        8.22347486e-02,  5.48575936e-02,  2.74391283e-02, -2.44929360e-16])

# Printing arrays
If an array is too large to ne printed, NumPy automatically skips the central part of the array and only prints the corners.

In [44]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]

In [42]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]

To disable this behavior and force NumPy to print the entire array, you can change the pricing options using 'set_printoptions'.

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported

# Basic Operations
Arithmetic operators on arrays apply 'elementwise'. A new array is created and filled with the result.

In [47]:
a=np.array([20,30,40,50])
b=np.arange(4)
c=a-b
c

array([20, 29, 38, 47])

In [48]:
b**2

array([0, 1, 4, 9])

In [49]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [50]:
a<35

array([ True,  True, False, False])

Unlike in many matrix languages, the product operator '*' operates elementwise in NumPy arrays. 

The matrix product can be performing using the '@' operator (in python>=3.5) or the 'dot' function or method

In [ ]:
A=np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])

A*Bv # elementwise product

array([[2, 0],
       [0, 4]])

In [52]:
A@B #matrix product

array([[5, 4],
       [3, 4]])

In [53]:
A.dot(B) #another matrix product

array([[5, 4],
       [3, 4]])

Some operations, such as '+=' and '*=', act in place to modify an existing array rather than create a new one.

In [56]:
rg=np.random.default_rng(1) # create instance of default random number generator
a=np.ones((2,3),dtype=int)
b=rg.random((2,3))
a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [57]:
b+=a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [58]:
a+=b #b is not automatically converted to integer type

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [60]:
a=np.ones(3, dtype=np.int32)
b=np.linspace(0, pi,3)
b.dtype.name

'float64'

In [61]:
c=a + b
c

array([1.        , 2.57079633, 4.14159265])

In [65]:
d=np.exp(c*1j,dtype=np.complex64)
d

array([ 0.5403023 +0.84147096j, -0.84147096+0.5403024j ,
       -0.54030246-0.8414709j ], dtype=complex64)

In [66]:
d.dtype.name

'complex64'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the 'ndarray' class.

In [67]:
a=rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [68]:
a.sum()

np.float64(3.1057109529998157)

In [69]:
a.min()

np.float64(0.027559113243068367)

In [70]:
a.max()

np.float64(0.8277025938204418)

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the 'axis' parameter you can apply an operation along the specified axis of an array:

In [71]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
b.sum(axis=0) # sum of each column

array([12, 15, 18, 21])

In [73]:
b.min(axis=1) # min of each row

array([0, 4, 8])

In [74]:
b.cumsum(axis=1) #cumulative sum of each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp.
In NumPy, these are called "universal functions" (ufunc).
Within Numpy, these functions operate elementwise on an array as output.

In [75]:
B=np.arange(3)
B

array([0, 1, 2])

In [76]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [77]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [78]:
C=np.array([2.,-1.,4.])
np.add(B,C)

array([2., 0., 6.])

# Indexing, slicing, and iterating
## One-dimensional 
These arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [79]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [80]:
a[2]

np.int64(8)

In [81]:
a[2:5]

array([ 8, 27, 64])

In [85]:
# equivalent to a[0:6:2]=1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:9:3]=1000
a

array([1000,    1, 1000, 1000, 1000,  125, 1000,  343,  512,  729])

In [90]:
a[::-1]
a

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

## Multidimensional
These arrays can have one index per axis. These indices are given in a tuple seperated by commas:

In [94]:
def f(x,y):
    return 10*x+y
b=np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [95]:
b[2,3]

np.int64(23)

In [96]:
b[0:5,1] # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [97]:
b[:,1] # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [98]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the no. of axes, the missing indices are considered complete slices

In [99]:
b[-1] # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

The expressions within the brackets in b[i] is treated as an 'i' followed by as many instances of ':' as needed to represent the remaining axes. 
NumPy also allows you to write this using dots as b[i,...].
The dots (...) represents as many colons as needed to produce a complete indexing tuple.
For example, if 'x' is an array with 5 axes, then:
. x[1,2, ...] is equivalent to x[1,2,:,:,:]
. x[...,3] to x[:,:,:,:,3]
. x[4,...,5,:] to x[4,:,:,5,:]

In [100]:
c=np.array([[[0,1,2],[10,12,13]],[[100,101,102],[110,112,113]]]) # a 3D array (two stacked 2D arrays)
c.shape

(2, 2, 3)

In [101]:
c[1,...] # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [102]:
c[...,2] # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

Iterating over multidimensional arrays is done with respect to the first axis:

In [103]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]

If one wants to perform an operation on each element in the array, one can use the 'flat' attribute which is an iterator over all the elements of the array.

In [104]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43

# 10 minuutes to pandas
Customarily, we import as follows:

import numpy as np

import pandas as pd

## Basic data structures in pandas
pandas provides two types of classes for handling data:
1. Series: a 'one-dimensional labeled array holding data of any type' such as integers, strings, Python objects etc.
2. DataFrame: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

## Object creation
Creating a Series by passing a list of values, letting pandas create a default 'RangeIndex'.

In [106]:
import pandas as pd
import numpy as np
s=pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Creating a DataFrame by passing a NumPy array with a datetime index using 'date_range()' and labeled columns:

In [107]:
dates=pd.date_range("20130101",periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [108]:
df=pd.DataFrame(np.random.randn(6,4), index=dates,columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.318614  1.355340 -1.254059  0.581532
2013-01-02 -1.050611 -0.071429  2.112334  1.196160
2013-01-03  0.673741  0.165823  0.425534  0.204611
2013-01-04 -0.253894 -0.385005  0.663758 -0.294077
2013-01-05  1.163838 -0.458342  1.260287 -0.821892
2013-01-06  0.223763  0.440419  1.543977 -1.809325

Creating a DataFrame by passing a dictionary of objects where the keys are the column labels and the values are the column values.

In [109]:
df2=pd.DataFrame({
    "A":1.0,
    "B":pd.Timestamp("20130102"),
    "C":pd.Series(1, index=list(range(4)),dtype="float32"),
    "D":np.array([3]*4,dtype="int32"),
    "E":pd.Categorical(["test","train","test","train"]),
    "F":"foo"
})
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

The columns of the resulting 'DataFrame' have different dtypes:

In [110]:
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

## Viewing data
Use the DataFrame.head() and DataFrame.tail() to view the top and bottom rows of the frame respectively:

In [111]:
df.head()

                   A         B         C         D
2013-01-01  0.318614  1.355340 -1.254059  0.581532
2013-01-02 -1.050611 -0.071429  2.112334  1.196160
2013-01-03  0.673741  0.165823  0.425534  0.204611
2013-01-04 -0.253894 -0.385005  0.663758 -0.294077
2013-01-05  1.163838 -0.458342  1.260287 -0.821892

In [112]:
df.tail()

                   A         B         C         D
2013-01-02 -1.050611 -0.071429  2.112334  1.196160
2013-01-03  0.673741  0.165823  0.425534  0.204611
2013-01-04 -0.253894 -0.385005  0.663758 -0.294077
2013-01-05  1.163838 -0.458342  1.260287 -0.821892
2013-01-06  0.223763  0.440419  1.543977 -1.809325

Display the 'DataFrame.index' or 'DataFrame.columns':

In [113]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [115]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

Return a NumPy representation of the underlying data with Datarame.to_numpy() without the index or column labels

In [116]:
df.to_numpy()

array([[ 0.31861443,  1.35534041, -1.25405875,  0.58153159],
       [-1.0506115 , -0.07142897,  2.11233437,  1.1961596 ],
       [ 0.67374114,  0.16582322,  0.4255336 ,  0.20461088],
       [-0.25389435, -0.38500504,  0.66375787, -0.29407694],
       [ 1.16383785, -0.45834153,  1.26028651, -0.82189191],
       [ 0.22376342,  0.44041903,  1.54397721, -1.80932473]])

## NOTE
#### NumPy arrays have one dtype for the entire array while pandas DataFrame have one dtype per column.
When you call 'DataFrame.to_numpy()', pandas will find the NumPy dtype that can hold 'all' of the dtypes in the DataFrame.
If the common data type is object, 'DataFrame.to_numpy()' will require copying data.

In [117]:
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

In [118]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

'describe()' shows a quick statistic summary of your data:

In [119]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.179242  0.174468  0.791972 -0.157165
std    0.766226  0.669207  1.171763  1.067547
min   -1.050611 -0.458342 -1.254059 -1.809325
25%   -0.134480 -0.306611  0.485090 -0.689938
50%    0.271189  0.047197  0.962022 -0.044733
75%    0.584959  0.371770  1.473055  0.487301
max    1.163838  1.355340  2.112334  1.196160

Transposing your data: Converting Rows to Columns and vice versa.

In [120]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.318614   -1.050611    0.673741   -0.253894    1.163838    0.223763
B    1.355340   -0.071429    0.165823   -0.385005   -0.458342    0.440419
C   -1.254059    2.112334    0.425534    0.663758    1.260287    1.543977
D    0.581532    1.196160    0.204611   -0.294077   -0.821892   -1.809325